name = "hackletter-website"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [ 
  { binding = "__LOADER_CACHE", id = "b588cafdd45041989fb623b5a6377758" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
